ALTER TABLE companies
ADD COLUMN IF NOT EXISTS profile_json TEXT NOT NULL DEFAULT '';

ALTER TABLE companies
DROP COLUMN IF EXISTS decision,
DROP COLUMN IF EXISTS confidence,
DROP COLUMN IF EXISTS evidence,
DROP COLUMN IF EXISTS raw;

ALTER TABLE people
DROP COLUMN IF EXISTS raw;
